name: GEekTimeMain

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Build and run GEekTimeMain
      run: |
        javac GEekTimeMain.java
        java GEekTimeMain
